# .github/conjur/authn-config.yml
authenticator_name: github-ci
service_id: conjur/authn-jwt/ConjurGit2
jwks-uri:  https://token.actions.githubusercontent.com/.well-known/jwks
issuer: https://token.actions.githubusercontent.com
identity-path: data/myspace
token-app-property: repository
