# .github/conjur/authn-config.yml
authenticator_name: ConjurGit2
service_id: conjur/authn-jwt/ConjurGit2
jwks_uri:  https://token.actions.githubusercontent.com/.well-known/jwks
jwt_issuer: https://token.actions.githubusercontent.com
identity_path: data/myspace
token_app_property: repository
