# .github/conjur/authn-config.yml
authenticator_name: ConjurGit
service_id: conjur/authn-jwt/ConjurGit
jwks-uri:  https://token.actions.githubusercontent.com/.well-known/jwks
issuer: https://token.actions.githubusercontent.com
identity-path: data/github
token-app-property: repository
