# .github/conjur/authn-config.yml
authenticator_name: ConjurGit
jwks_uri:  https://token.actions.githubusercontent.com/.well-known/jwks
jwt_issuer: https://token.actions.githubusercontent.com
identity_path: data/github
token_app_property: repository
