      - name: Exchange for Conjur session token
        id: conjur_auth
        shell: bash
        run: |
          set -euo pipefail
          CONJUR_URL="https://pwclab.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT="conjur"
          SERVICE_ID="GitMain2"

          # Mint GitHub OIDC JWT
          GIT_JWT=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                         "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

          # Call Conjur Cloud authenticate endpoint, request base64
          SESSION_TOKEN_B64=$(curl -s --request POST \
            "$CONJUR_URL/authn-jwt/${SERVICE_ID}/${CONJUR_ACCOUNT}/authenticate" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --header "Accept-Encoding: base64" \
            --data-urlencode "jwt=$GIT_JWT")

          echo "Base64 length: ${#SESSION_TOKEN_B64}"

          # 🔽 Decode the base64 into the JSON Secretless expects
          echo "$SESSION_TOKEN_B64" | base64 -d > session_token.json

          echo "Decoded JSON length: $(wc -c < session_token.json)"
          head -c 120 session_token.json; echo

          # Save both formats as artifacts if you want
          echo "$SESSION_TOKEN_B64" > session_token.b64

      - name: Upload decoded JSON token
        uses: actions/upload-artifact@v4
        with:
          name: conjur-session-json
          path: session_token.json

      - name: Upload raw base64 token
        uses: actions/upload-artifact@v4
        with:
          name: conjur-session-b64
          path: session_token.b64
