# .github/workflows/conjur-jwt-auth.yml
name: Conjur JWT Auth (Hardcoded)

on:
  workflow_dispatch:

jobs:
  conjur-auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for GitHub OIDC
      contents: read

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Authenticate to Conjur via GitHub OIDC (hardcoded)
        id: conjur_auth
        shell: bash
        run: |
          set -euo pipefail

          # ---- Hardcoded Conjur/GitHub OIDC config ----
          CONJUR_BASE_URL="https://pwclab.secretsmgr.cyberark.cloud"
          CONJUR_ACCOUNT="conjur"
          SERVICE_ID="Github_auth"
          OIDC_AUDIENCE="conjur-demo"
          AUTH_URL="${CONJUR_BASE_URL}/authn-jwt/${SERVICE_ID}/${CONJUR_ACCOUNT}/authenticate"
          # ---------------------------------------------

          echo "Requesting GitHub OIDC JWT for audience: ${OIDC_AUDIENCE}"
          REQ_URL="${ACTIONS_ID_TOKEN_REQUEST_URL}?audience=${OIDC_AUDIENCE}"

          JWT=$(curl -sS -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${REQ_URL}" | jq -r .value)

          if [ -z "${JWT}" ] || [ "${JWT}" = "null" ]; then
            echo "Failed to obtain GitHub OIDC token. Ensure 'permissions: id-token: write' is set."
            exit 1
          fi

          echo "GitHub JWT length: ${#JWT}"
          printf "%s" "${JWT}" > id_token.txt

          echo "Authenticating to Conjur at: ${AUTH_URL}"
          SESSION_TOKEN=$(curl -sS \
            --request POST "${AUTH_URL}" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --header "Accept-Encoding: base64" \
            --data-urlencode "jwt=${JWT}")

          if [ -z "${SESSION_TOKEN}" ]; then
            echo "Failed to obtain Conjur session token. Check authenticator config and audience."
            exit 1
          fi

          echo "Conjur session token length: ${#SESSION_TOKEN}"
          printf "%s" "${SESSION_TOKEN}" > session_token.txt

          # Expose as step outputs (optional for later steps)
          echo "jwt=${JWT}" >> "$GITHUB_OUTPUT"
          echo "session=${SESSION_TOKEN}" >> "$GITHUB_OUTPUT"

      - name: Upload raw jwt
        uses: actions/upload-artifact@v4
        with:
          name: raw-jwt
          path: id_token.txt

      - name: Upload raw session token
        uses: actions/upload-artifact@v4
        with:
          name: raw-session
          path: session_token.txt

      # Optional: decode session token and show authenticated user
      - name: Show whoami (optional)
        shell: bash
        run: |
          set -euo pipefail
          SESSION_TOKEN_B64=$(cat session_token.txt)
          # Conjur session token (base64) decodes to JSON with "user_id"
          USER=$(printf "%s" "${SESSION_TOKEN_B64}" | base64 --decode 2>/dev/null | jq -r .user_id || true)
          echo "Authenticated as: ${USER:-unknown}"

